### ISSUE TITLE
Configuration file argument missing in documentation

### ISSUE THREAD

**Issue by fbottarel** [robotology/stereo-vision#17]
While trying to figure out how to make SFM work with 640x480 camera resolution, I noticed that the camera config file `icubEyes.ini` in context `cameraCalibration` [is set as default](https://github.com/robotology/stereo-vision/blob/bf6b98fba5f50decb62cc6e388c9be3f044fd310/modules/SFM/SFM.cpp#L1412). This might be obvious for some, but inexperienced users like myself would need to look at the documentation and they wouldn't find this bit of information. 

Could you add the `--from [calibrationFile]` and `--context [calibrationContext]` command-line parameters explicitly in the docs?

**Comment by pattacini** [comment]
Hi @fbottarel 

Just fork this repo and open up a PR on this: it would be much simpler.

**Comment by pattacini** [comment]
Fixed via #18.

Thanks @fbottarel.
