### ISSUE TITLE
Disparity map calibration

### ISSUE THREAD

**Issue by samvinanzi** [robotology/stereo-vision#20]
Hello!

I have been having issues in obtaining a clean disparity map from our iCub (Manchester01) and I would benefit from some support.

These are the eyes home position when yarprobotinterface is running:

![eyes1](https://user-images.githubusercontent.com/29630254/51611034-24e15700-1f16-11e9-9378-8c68a0bcd75c.jpg)
![eyes2](https://user-images.githubusercontent.com/29630254/51611037-2743b100-1f16-11e9-9637-d1f49ef15652.jpg)

I have run stereoCalib with the standard chessboard printed on an A4 sheet, keeping it as close as possible to the cameras during the calibration phase and using the following parameters:

```
[STEREO_CALIBRATION_CONFIGURATION]
boardWidth 8
boardHeight 6
boardSize 0.024
numberOfPairs 20
```

Obtaining an error of more or less 0.2. The following is a view from the eyes after the calibration, using pinhole projection and the centercross:

![eyes_view](https://user-images.githubusercontent.com/29630254/51611045-2ca0fb80-1f16-11e9-936f-ffc5f1d3ff77.png)

At this point, I prepare a table with objects of different height and I try to calibrate SFM, but the procedure often fails and even when it succeeds, the resulting disparity map looks like a grey flickering blob. Here are two examples:

![sfm_1](https://user-images.githubusercontent.com/29630254/51611072-3aef1780-1f16-11e9-9abf-426a06f50529.png)
![sfm_2](https://user-images.githubusercontent.com/29630254/51611075-3c204480-1f16-11e9-8840-731eb2a77152.png)

(In this second picture, I tried to raise the table to the robot’s eye level instead of making it lower its gaze, plus I eliminated any background)

Of course, what I would like to obtain is something as clear as this example: [https://youtu.be/PqpHrxgJqfY](https://youtu.be/PqpHrxgJqfY)
Am I doing something wrong? Are there some other calibrations I should run? Any help will be highly appreciated :)

**Comment by pattacini** [comment]
Hi @samvinanzi 

The images you posted are not displayable actually. It might be that those links point to a private repository of yours. A possible workaround would be to **drag & drop** those pictures herein straight away.

**Comment by samvinanzi** [comment]
Oh, good to know that you can simply drag and drop!
By the way, they should be visible now.

**Comment by vtikha** [comment]
Hi @samvinanzi 

The first condition is the one typically used as the robot is able to have a wider range and sees different planes. Please try reducing the gain of the cameras as you are failing to detect features on the objects that are useful for SFM or maybe use less bland objects (at least for calibration). eg: You could use some books (put vertically) etc that are rich in features.

**Comment by samvinanzi** [comment]
I can't lower the gain of the cameras as it's already set to 0, but I've changed the scene and run some trials:

1) I've tried using the "default" parameters specified here: [http://www.icub.org/doc/icub-main/group__icub__dragonfly2.html](http://www.icub.org/doc/icub-main/group__icub__dragonfly2.html).

![screenshot from 2019-01-24 11-43-50](https://user-images.githubusercontent.com/29630254/51676635-215dd680-1fcf-11e9-83d9-4b5ba9eb6c4c.png)

2) I tweaked a bit those "default" parameters:

![screenshot from 2019-01-24 11-47-53](https://user-images.githubusercontent.com/29630254/51676637-23c03080-1fcf-11e9-8ff4-9c65952372d3.png)

3) I went back to our custom parameters, but I raised the sharpness and moved around the objects on the table. For sake of completeness, these are the parameters I'm using:
`yarpdev --device grabber --subdevice dragonfly2 --width 320 --height 240 --video_type 1 --white_balance 0.514 0.610 --gain 0.0 --shutter 0.913 --name /icub/cam/left --brightness 0 --DR2 --stamp --sharpness 1.0 --hue 0.48 --gamma 0.4 --saturation 0.420 --framerate 30 --guid 00b09d01006fb1fa`

![screenshot from 2019-01-24 11-51-52](https://user-images.githubusercontent.com/29630254/51676641-2589f400-1fcf-11e9-929d-4146668cf075.png)

As you can see, I didn't obtain any improvements.
Do you have any other ideas?

**Comment by GiuliaP** [comment]
Hi @samvinanzi 

you could also try changing some parameter of the `SFM` module (please refer to the module's [documentation](http://robotology.github.io/stereo-vision/doxygen/doc/html/group__SFM.html)).

You could try:
- switching from `elas` to the `sgbm` algorithm for disparity computation (by passing the `--use_sgbm` parameter)
- if you keep `elas`, you could try changing the following parameters:
    - `–elas_setting MIDDLEBURY` instead of the default `–elas_setting ROBOTICS`
    - `–elas_add_corners` if you want a major coverage of the image
    - `–elas_ipol_gap_width 20` instead of the default (40) if you prefer holes instead of a larger disparity interpolation

Giulia

**Comment by samvinanzi** [comment]
Thank you too for the suggestions!

Several combinations of parameters for LIBELAS didn't bring much improvement (I like the effect that is given by `--elas_add_corners`, but overall the output still looks like a meaningless gray surface).

SGBM gave better results, in my opinion, but there is still something strange about it: you still can't really distinguish the scene in the disparity map, plus it seems like there is a vertical black band on the left side. Here is what it looks like (I also added the rectified images, they might help):

![screenshot from 2019-01-24 15-19-39](https://user-images.githubusercontent.com/29630254/51688119-d4d4c400-1feb-11e9-8b61-a964fa18bb41.png)

**Comment by pattacini** [comment]
Just wanted to share here a pointer to a similar issue: https://github.com/robotology/icub-support/issues/163.

**Comment by samvinanzi** [comment]
> Just wanted to share here a pointer to a similar issue: [robotology/icub-support#163](https://github.com/robotology/icub-support/issues/163).

Thank you for pointing it out. I was aware of that issue and, actually, the reason why I provided pictures of iCub's eyes and views was to pinpoint any possible mechanical errors (e.g. displaced eyebulbs, unfocused lens, etc...) as was the case for the Barcelona team.
