### ISSUE TITLE
toCvMat breaks SFM disparity output

### ISSUE THREAD

**Issue by damianomal** [robotology/stereo-vision#21]
While testing current SFM code using an external laptop, I found that there has been a [commit](https://github.com/robotology/stereo-vision/commit/4cc9115d8fb21fd698f0a21dd504df24260863c0#diff-4389744824802b5408b3539863c413ac) which probably breaks the functionalities of the module.

More precisely, the `toCvMat` function used here

https://github.com/robotology/stereo-vision/blob/23c45483ae03fc630a2ddf5a85c039f85905afc2/modules/SFM/SFM.cpp#L401-L421

causes the disparity map in output to be black. 

We tried to visualize it with `cv::imshow` and the disparity itself is correctly computed and visualized, thus I believe there's something wrong with `toCvMat`.

The current branch used on `iCubGenova01` is ok, we should be careful when updating the machines, before this issue will be fixed.

**Comment by pattacini** [comment]
Thanks @damianomal for spotting this.

The introduction of `toCvMat`/`fromCvMat` together with the need for updating the code to the use of `cv::Mat` has brought about quite devastating effects 😢 

Honestly, I don't know offhand how to fix this. Perhaps, @Nicogene can suggest the correct workaround.

**Comment by xEnVrE** [comment]
@damianomal 

Can you try to change the code to

```
if (!outputDm.empty()) 
     { 
         ImageOf<PixelMono> &outim = outDisp.prepare(); 
         Mat outimMat;
         if (doBLF) 
         { 
             Mat outputDfiltm; 
             cv_extend::bilateralFilter(outputDm,outputDfiltm, sigmaColorBLF, sigmaSpaceBLF); 
             outimMat = outputDfiltm; 
         } 
         else 
         { 
             outimMat = outputDm; 
         } 
         outim = fromCvMat<PixelMono>(outimMat);
         outDisp.write(); 
} 
```
?

**Comment by pattacini** [comment]
Good point @xEnVrE 
Your snippet could make it work.

Actually, operations like `outimMat=outputDm` in the first hand don't copy out the whole Mat but rather the header; that's probably why the original code isn't fine.

On the other hand, `fromCvMat<>` should elicit an entire copy inside 👍

**Comment by damianomal** [comment]
@xEnVrE's fix works :wink: thank you!

**Comment by pattacini** [comment]
Awesome! Could you then open up a PR @damianomal ?

**Comment by Nicogene** [comment]
Good job @xEnVrE , it is the right usage of `YARP_cv` :medal_military: 

![image](https://user-images.githubusercontent.com/19152494/58343513-7d3c4d00-7e53-11e9-88b2-1a8afad9dc09.png)

**Comment by pattacini** [comment]
Fix pushed to `master` @damianomal
