### ISSUE TITLE
Clarify license of the external code vendored in the repo

### ISSUE THREAD

**Issue by traversaro** [robotology/stereo-vision#26]
The repo README says that the code contained in the repo  is licensed under the GPL2+ license. However, as the repo also include some vendored libraries, I think it is important to clearly state the license of the vendored libraries, including:
* libelas (vendored in https://github.com/robotology/stereo-vision/tree/e8e064ef20d8888437f94e76819bc53cf580bf2e/lib/src/elas) : this is licensed under GPL3+ 
*  zhangyou_sgbm_cuda (vendored in https://github.com/robotology/stereo-vision/tree/master/modules/DisparityModule/sgbm_cuda ): the license of this library is not clear in the original repo ( https://github.com/jasonlinuxzhang/sgbm_cuda ) 

cc @maggia80 @pattacini

**Comment by pattacini** [comment]
cc @GiuliaP @damianomal

**Comment by GiuliaP** [comment]
Thanks for reporting. Would it be fine if I
- modify the README's License section, by clarifying that the `libelas` is under the GPL3+ license
- add the LICENSE file to the `lib/src/elas` directory?

**Comment by pattacini** [comment]
We may proceed as done in https://github.com/icub-tech-iit/ventilator-FI5#-license.

What do you think @traversaro ?

**Comment by traversaro** [comment]
Sure! Technically speaking any resulting binary that gets linked with [`GPL-3.0-or-later`](https://spdx.org/licenses/GPL-3.0-or-later.html) code can only be distributed under the  [`GPL-3.0-or-later`](https://spdx.org/licenses/GPL-3.0-or-later.html)  license, but as we license the rest of code as  [`GPL-2.0-or-later`](https://spdx.org/licenses/GPL-2.0-or-later.html)  that is ok.

**Comment by pattacini** [comment]
So @GiuliaP, we could do the following:
1. >modify the README's License section, by clarifying that the libelas is under the GPL3+ license

    ✔ Yes, but let's refactor the main section as in https://github.com/icub-tech-iit/ventilator-FI5#-license, if possible.

2. >add the LICENSE file to the `lib/src/elas` directory?

    ✔ Yes, given that it won't harm. 


Would this be sufficient for what concerns `elas` @traversaro ?

**Comment by traversaro** [comment]
Yes!

**Comment by GiuliaP** [comment]
Thanks for the suggestion, I will do it by next tuesday if it's ok.

**Comment by GiuliaP** [comment]
@pattacini : I have applied the modifications (by directly pushing to master since it was not involving code changes). 

I have modified the main README (`Installation` and `License`) and created one [README](https://github.com/robotology/stereo-vision/blob/master/lib/include/iCub/stereoVision/elas/README.md) where I clarify the changes to LIBELAS and point to the LICENSE and the original LIBELAS' README, which I have also added in the same folder.

**Comment by pattacini** [comment]
Fantastic 👍🏻 
Thanks @GiuliaP

**Comment by pattacini** [comment]
What do we do with `sgbm_cuda`?
@traversaro @damianomal

**Comment by vtikha** [comment]
As far as I know it is an optional algorithm to be used to compare results with non cuda versions. A user can choose between sgbm, sgbm_cuda, libelas..

**Comment by pattacini** [comment]
That's correct @vtikha 👍🏻 
We were just discussing what to do in terms of the license, as `sgbm_cuda` is vendored alongside this repo.

**Comment by vtikha** [comment]
Ah ok, I misunderstood your comment as a question of what is it used for. Sorry. For the licence I guess we need to contact the author to update his license, but there has not been an activity on that repo for about two years. Other option consider removing it/alternative?

**Comment by pattacini** [comment]
We've just asked @damianomal to show up as `sgbm_cuda` is vendored inside his `DisparityModule`.

See https://github.com/robotology/stereo-vision/issues/26#issue-720212599.

**Comment by damianomal** [comment]
I apologize for the late reply, I'll try to contact the original author of the project and I will update with a comment here as soon as I get an answer.

When writing to the author, should I specify something in particular about the nature of the project (i.e. this repo) in which their repository has been used?

**Comment by pattacini** [comment]
>When writing to the author, should I specify something in particular about the nature of the project (i.e. this repo) in which their repository has been used?

You could cite this repo, yep, saying that we're making use of the original code 👍🏻

**Comment by pattacini** [comment]
@damianomal any news on this?

**Comment by damianomal** [comment]
@pattacini unfortunately I still have no updates, I tried to contact the author also on what seems to be his Linkedin account, with no success whatsoever

**Comment by pattacini** [comment]
Ok thank you!
I think that we can close this then.
