### ISSUE TITLE
Compilation error for OpenCV nonfree components

### ISSUE THREAD

**Issue by carlomazzola** [robotology/stereo-vision#33]
Hi all,

I'm trying to compile the stereo-vision module but it returns the following error:

fatal error: opencv2/xfeatures2d/nonfree.hpp: No such file or directory
   27 |         #include <opencv2/xfeatures2d/nonfree.hpp>
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I saw in the documentation that the SIFT are among the dependencies. Is the error related to this, or the reason is another one?
I use an Ubuntu 20 machine with Yarp 3.5.1 and OpenCV 4.2.0 installed.

Thanks!

**Comment by pattacini** [comment]
Hi @carlomazzola 

How did you install OpenCV 4.2.0?

**Comment by carlomazzola** [comment]
Hi @pattacini, 

it is the default version that is already present in Ubuntu 20.04. we recently installed it in the machine of the robot.

**Comment by pattacini** [comment]
The default version ain't shipped with the nonfree modules.

You ought to clone the `opencv` repo locally together with `opencv_contrib` and configure the project with the proper CMake flags.

The process is pretty much resumed at https://github.com/robotology/iol#dependencies.

You should most likely remove the default OpenCV to prevent clashes.

**Comment by pattacini** [comment]
I've made the README more explicit about that.
See #34.

**Comment by carlomazzola** [comment]
Thank you for adding the information in the readme. 
Yes, we installed everything with the superbuild.

**Comment by pattacini** [comment]
>Yes, we installed everything with the superbuild.

So, I'd recommend that you do the following, in order:
1. Uninstall the apt version of OpenCV from that PC.
2. Build OpenCV + contrib modules as reported above.
    - If you opt for `make install`, then you're done.
    - Alternatively, if you stick to the build, you have to export the env var `OpenCV_DIR` pointing to build location.
3. Rebuild the superbuild.
4. Rebuild `stereo-vision`.

Hope this helps out.

**Comment by pattacini** [comment]
Closing for now.
Feel free to open it up again if required.
