### ISSUE TITLE
BottleImpl error when calling Flood3D on a black seed

### ISSUE THREAD

**Issue by tanismar** [robotology/stereo-vision#9]
Hi, 
I have realized that when SFM is called with the "Flood3D" command, giving as a seed point a point which is not defined (black in the disparity image), instead of returning an empty bottle or other kind of graceful handling, it generates the following error:
yarp: BottleImpl reader failed, unrecognized object code 25
By the way, this does not make the SFM module crash, but blocks the rpc port and whatever module that was communicating with SFM. 
Can this situation be handled, so that SFM will return, for example, an empty bottle?
Best, 
Tanis

**Comment by tanismar** [comment]
Hi! I just tested the fix (after pulling of course), and the error persists:

Flood3D 10 216 0.01
yarp: BottleImpl reader failed, unrecognized object code 25

Also noticed that while on the blob reconstructor is called with "Flood3D", if "flood3D" is called, an output is given too (which is not the same from "Flood3D"). This can be confusing/lead to error when calling the other function.

**Comment by tanismar** [comment]
my bad, I was a little bit on a hurry and pulled on another folder. So... I still have to test it.

**Comment by pattacini** [comment]
So let's close it again; pretty sure it is fixed.
Reopen it otherwise :wink:.
